trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '14'
    checkLatest: true

- script: |
    npm install -g firebase-tools
    npm install
  displayName: 'Instalar Firebase CLI e Dependências do Projeto'

- script: |
    npm run build
    firebase deploy --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT"
  displayName: 'Compilar e Fazer o Deploy no Firebase'
  env:
    FIREBASE_TOKEN: $(FIREBASE_TOKEN)
    FIREBASE_PROJECT: 'seu-projeto-firebase' 

